services:
  rasa:
    image: rasa/rasa:3.6.20-full
    volumes:
      - .:/app
    ports:
      - 5005:5005
    networks:
      - my-project
    command: run --enable-api --cors "*"

  action-server:
    build:
      context: .
      dockerfile: actions/Dockerfile
    volumes:
      - ./actions:/app/actions
      # PARTILHA DA KNOWLEDGE BASE
      - ./vector_store:/app/vector_store 
      - ./models:/app/models # <--- Adicionado: Pasta local : Pasta no container
    ports:
      - 5055:5055
    networks:
      - my-project
    depends_on:
      - db
    environment:
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      DB_HOST: db # Gafe: Adicionado para o código saber onde está a BD
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASS}
      POSTGRES_DB: ${APP_DATABASE_NAME}

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-project
    environment:
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASS}
      POSTGRES_DB: ${APP_DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - my-project

  flask-server:
    build:
      context: .
      dockerfile: flask_backend/Dockerfile
    depends_on:
      - db
    volumes:
      - ./flask_backend:/app/flask_backend
      # PARTILHA DA KNOWLEDGE BASE (Faltava isto!)
      - ./vector_store:/app/vector_store 
      # Mount para os uploads temporários (opcional mas recomendado)
      - ./temp_uploads:/app/temp_processing
      - ./models:/app/models
    ports:
      - 8080:8080
    networks:
      - my-project
    environment:
      DB_HOST: db # Gafe: Importante para a ligação SQLAlchemy/Psycopg2
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASS}
      POSTGRES_DB: ${APP_DATABASE_NAME}
      MOODLE_TOKEN: ${MOODLE_TOKEN}
      MOODLE_COURSE_ID: ${MOODLE_COURSE_ID}
      MOODLE_URL: ${MOODLE_URL}
      MOODLE_COURSE_SHORTNAME: ${MOODLE_COURSE_SHORTNAME}
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}" # Gafe: O Flask pode precisar para os embeddings

networks:
  my-project:

volumes:
  postgres_data: