services:
  rasa:
    image: rasa/rasa:3.6.20-full
    volumes:
      - .:/app
    ports:
      - 5005:5005
    networks:
      - my-project
    command: run --enable-api --cors "*"

  action-server:
    build:
      context: .
      dockerfile: actions/Dockerfile
    user: "0:0"  # Força o utilizador Root (UID 0)
    entrypoint: [] # Limpa o script padrão da Rasa
    command: ["/opt/venv/bin/python", "-m", "rasa_sdk", "--actions", "actions", "--port", "5055"]
    volumes:
      - ./actions:/app/actions
      # PARTILHA DA KNOWLEDGE BASE
      - ./vector_store:/app/vector_store 
      - ./models:/app/models # <--- Adicionado: Pasta local : Pasta no container
    ports:
      - 5055:5055
    networks:
      - my-project
    depends_on:
      - db
      - chroma
    environment:
      PYTHONUNBUFFERED: "1" # Para ver os logs em tempo real
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      DB_HOST: db # Gafe: Adicionado para o código saber onde está a BD
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASS}
      POSTGRES_DB: ${APP_DATABASE_NAME}

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-project
    environment:
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASS}
      POSTGRES_DB: ${APP_DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - my-project

  flask-server:
    build:
      context: .
      dockerfile: flask_backend/Dockerfile
    user: "0:0"
    depends_on:
      - db
      - chroma
    volumes:
      # MAPEAMENTO CORRETO: A pasta local vai para dentro da pasta /app inteira
      - ./flask_backend:/app
      - ./vector_store:/app/vector_store 
      - ./models:/app/models
    ports:
      - 8082:8080
    networks:
      - my-project
    environment:
      PYTHONPATH: "/app"
      PYTHONUNBUFFERED: "1"
      FLASK_APP: "app.py"  # Forçamos o Flask a focar-se no ficheiro certo
      FLASK_ENV: "development"
      DB_HOST: db 
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASS}
      POSTGRES_DB: ${APP_DATABASE_NAME}
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"

  chroma:
    image: chromadb/chroma:latest
    command: ["run", "--path", "/chroma/data", "--port", "8000", "--host", "0.0.0.0"]
    volumes:
      - ./vector_store:/chroma/data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/data
      - ANONYMIZED_TELEMETRY=False
    ports:
      - "8000:8000"
    networks:
      - my-project

networks:
  my-project:

volumes:
  postgres_data: